# Generated by Django 4.0 on 2022-03-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentpred', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocr',
            name='education',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='ocr',
            name='email',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='ocr',
            name='income',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='ocr',
            name='name',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='ocr',
            name='passw',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
