# Generated by Django 4.0 on 2022-03-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentpred', '0002_ocr_education_ocr_email_ocr_income_ocr_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocr',
            name='passw1',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
