# Generated by Django 4.0 on 2022-03-04 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentpred', '0003_ocr_passw1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocr',
            name='education',
            field=models.CharField(default='Education', max_length=100),
        ),
        migrations.AlterField(
            model_name='ocr',
            name='email',
            field=models.CharField(default='Email', max_length=100),
        ),
        migrations.AlterField(
            model_name='ocr',
            name='income',
            field=models.CharField(default='Income', max_length=100),
        ),
        migrations.AlterField(
            model_name='ocr',
            name='name',
            field=models.CharField(default='name ', max_length=100),
        ),
        migrations.AlterField(
            model_name='ocr',
            name='passw',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ocr',
            name='passw1',
            field=models.CharField(default='', max_length=100),
        ),
    ]
