# Generated by Django 3.2.12 on 2022-03-05 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentpred', '0004_alter_ocr_education_alter_ocr_email_alter_ocr_income_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocr',
            name='passw1',
        ),
    ]
