# Generated by Django 3.2.12 on 2022-03-05 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentpred', '0005_remove_ocr_passw1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocr',
            name='education',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='ocr',
            name='income',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
